name: Run Tests
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Copy .env.example to .env
      run: cp .env.example .env
    - name: Create folders
      run: |
          mkdir -p cache/tts
          mkdir -p uploads/photos
          mkdir -p media/recipes
    - name: Start server
      run: make up &
    - name: Wait for containers to be ready
      run: |
        until curl -s http://localhost:8000/health; do
          echo "Waiting for service startup..."
          sleep 5
        done
    - name: Run tests
      run: make test
    - name: Stop server
      if: always()
      run: make down
