name: Run Tests
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Copy .env.example to .env
      run: cp .env.example .env
    - name: List all files recursively
      run: ls -R
    - name: Create folders
      run: |
          mkdir -p cache/tts
          mkdir -p uploads/photos
          mkdir -p media/recipes
          mkdir -p htmlcov
    - name: Start server
      run: make up &
    - name: Wait for service startup
      run: |
        until curl -s http://localhost:8000; do
          echo "Waiting for service startup..."
          sleep 5
        done
    - name: Run tests
      run: docker compose exec app make test-cov
    - name: List all files recursively
      run: ls -R
    - name: Upload tests report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: tests-report
        path: htmlcov/
        retention-days: 7
    - name: Stop server
      if: always()
      run: make down
