name: Run Tests
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Docker Setup Compose
      uses: docker/setup-compose-action@v1.2.0
    - name: Start server
      run: make up
    - name: Run tests
      run: make test
    - name: Stop server
      if: always()
      run: make down
