name: Run Tests
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Copy .env.example to .env
      run: cp .env.example .env
    - name: Start server
      run: docker compose -f docker-compose.yml -f docker-compose.ci.yml up -d
    - name: Wait for service startup
      run: |
        until curl -s http://localhost:8000; do
          echo "Waiting for service startup..."
          sleep 5
        done
    - name: Run tests
      run: docker compose exec app pytest --tb=short --disable-warnings -c pytest.ini --html=tests-report.html --self-contained-html --cov=app --cov-report=term --cov-report=html
    - name: Upload coverage report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: htmlcov/
        retention-days: 7
    - name: Upload tests report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: tests-report
        path: tests-report.html
        retention-days: 7
    - name: Stop server
      if: always()
      run: docker compose down
